# Generated by Django 3.2.3 on 2021-09-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_alter_article_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='cat_slug',
        ),
    ]
