# Generated by Django 3.2.3 on 2021-09-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_rename_slug_category_cat_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_slug',
            new_name='slug',
        ),
    ]
